### PR TITLE
Add CHANGELOG.md template, use README.md as mdoc index.md

### PR DESCRIPTION
**Pull request by er1c**
Not sure what you think about this, but it seems a bit more convenient to use the `README.md` as the initial mdoc site and throwing in the CHANGELOG.md.

### CODE REVIEW

**Comment by alexandru** [comment]
This might be a good idea, yes.

Have you tested it?

**Comment by er1c** [comment]
@alexandru I need to do an sbt new from the PR branch.  These were quick-hacks for something I've been changing ad-hoc recently and wanted to get you feedback before spending more time on it.   Which parts are fine? Change Log/README/etc?

https://github.com/er1c/fm-common is an example project with the changes (See https://github.com/er1c/fm-common/blob/main/build.sbt#L271)

**Comment by er1c** [comment]
@alexandru just noticed one issue: https://er1c.github.io/fm-common/

image

The links to the md files don't work out of the box, might be something simple, not sure if you know offhand.

**Comment by alexandru** [comment]
I think both having a CHANGELOG and having the README.md as the index is good.

On the `LICENSE.md`, normally Jekyll can link automatically to `.md` links, however it needs this plugin to work:

https://github.com/benbalter/jekyll-relative-links

**Comment by er1c** [comment]
@alexandru closed? I had it on my todo list to update this and look into the relative links, do I just need to re-open when ready?

**Comment by alexandru** [comment]
@er1c I did not close it, I don't know what happened. And I can't reopen it.

Can you re-submit it?

**Comment by alexandru** [comment]
@er1c I just renamed `master` to `main`. Maybe that's why it was closed.

**Pull request closed without merging**
