### PR TITLE
Bpg patch 1

### PR DESCRIPTION
**Pull request by bpg**

### CODE REVIEW

**Comment by bpg** [comment]
wrong repo

**Comment by alexandru** [comment]
Hi @bpg, I'm assuming this PR was submitted by mistake?

I see some cool things in it I might borrow, like `styfle/cancel-workflow-action@0.4.0`, that's a good idea.

**Comment by bpg** [comment]
Hi @alexandru, yes it was for my fork, by GH always puts the upstream repo as a default :)
Feel free to borrow anything. I'm not sure if it makes sense to merge it back tho... I've added some specific dependencies and made a few other changes.

**Comment by bpg** [comment]
Oh, and you may need this change https://github.com/alexandru/typelevel-library.g8/pull/88/commits/beaac8274663860c97f490df0752479f97846a62 -- my builds started failing on CI

**Pull request closed without merging**
